# Generated by Django 5.2 on 2025-04-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaPracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('lokalizacja', models.CharField(max_length=100)),
                ('wynagrodzenie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_dodania', models.DateField()),
                ('data_wygasniecia', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilKandydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('cv_sciezka', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilPracodawcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=100)),
                ('strona_www', models.URLField(blank=True)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('typ_uzytkownika', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaKategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kategoria')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ofertapracy')),
            ],
        ),
        migrations.CreateModel(
            name='Aplikacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplikacji', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('list_motywacyjny_sciezka', models.CharField(max_length=255)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ofertapracy')),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profilkandydata')),
            ],
        ),
        migrations.AddField(
            model_name='ofertapracy',
            name='pracodawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profilpracodawcy'),
        ),
        migrations.AddField(
            model_name='profilpracodawcy',
            name='uzytkownik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.uzytkownik'),
        ),
        migrations.AddField(
            model_name='profilkandydata',
            name='uzytkownik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.uzytkownik'),
        ),
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosci_wyslane', to='myapp.uzytkownik')),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosci_odebrane', to='myapp.uzytkownik')),
            ],
        ),
    ]
