# Generated by Django 5.2 on 2025-05-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertapracy',
            name='tytul',
        ),
        migrations.RemoveField(
            model_name='ofertapracy',
            name='wynagrodzenie',
        ),
        migrations.AddField(
            model_name='ofertapracy',
            name='branza',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ofertapracy',
            name='stanowisko',
            field=models.CharField(choices=[('programista', 'Programista'), ('analityk', 'Analityk'), ('sprzedawca', 'Sprzedawca')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='ofertapracy',
            name='data_dodania',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ofertapracy',
            name='lokalizacja',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ofertapracy',
            name='status',
            field=models.CharField(default='aktywny', max_length=20),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='haslo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='typ_uzytkownika',
            field=models.CharField(choices=[('kandydat', 'Kandydat'), ('pracodawca', 'Pracodawca')], max_length=20),
        ),
    ]
