# Generated by Django 5.2 on 2025-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_ofertapracy_tytul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplikacja',
            name='miejsce_zamieszkania',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aplikacja',
            name='staz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplikacja',
            name='wiek',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplikacja',
            name='wyksztalcenie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aplikacja',
            name='list_motywacyjny_sciezka',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
