# Generated by Django 5.2 on 2025-05-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_aplikacja_miejsce_zamieszkania_aplikacja_staz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wymaganie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=255)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wymagania', to='myapp.ofertapracy')),
            ],
        ),
        migrations.CreateModel(
            name='OdpowiedzNaWymaganie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelnia', models.BooleanField()),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profilkandydata')),
                ('wymaganie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wymaganie')),
            ],
        ),
    ]
